services:
  llamacpp:
    image: joshxt/local-llm:cpu-f99ed54d76d3752a2af75979dd06f3ef52247a6d
    restart: unless-stopped
    volumes:
      - ./models:/app/models

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
    ports:
      - ${MONGODB_PORT}:${MONGODB_PORT}
    volumes:  # Persist the data
      - ./data:/data/db

  backend:
    image: ${DOCKER_REGISTRY}/zenbox-backend
    depends_on:
      - mongo
      - llamacpp
    env_file:
      - ./.env
    volumes:
      - ./logs/backend:/app/logs

  api:
    image: ${DOCKER_REGISTRY}/zenbox-backend-api
    depends_on:
      - mongo
    env_file:
      - ./.env
    volumes:
      - ./logs/api:/app/logs

  nextjs-app:
    image: ${DOCKER_REGISTRY}/zenbox-nextjs-app
    depends_on:
      - mongo
    env_file:
      - ./.env
    volumes:
      - ./logs:/app/logs

  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ${SSL_CERT_PATH}:/etc/nginx/ssl/my_ssl_cert.crt
      - ${SSL_KEY_PATH}:/etc/nginx/ssl/my_ssl_key.key
    depends_on:
      - nextjs-app
